version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  backend:
    build: .
    container_name: invoice-backend
    depends_on:
      - minio
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: invoices
      GEMINI_API_KEY: ${GEMINI_API_KEY:-test}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always

volumes:
  minio_data:
